### PR TITLE
Milestone: Friendship v2

### PR DESCRIPTION
**Pull request by jcy2704**
### Friendship V2 Features
**For this Milestone we added composite keys for the Friendship table and removed logic from the views and refactored it inside the helpers.**
- Composite Primary Keys in Friendship table
- Partial form for Accept and Decline
- Removed logic from views
- Added refactored logic in users helper

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team! I don't seem to find the implementation of the core features for this milestone i.e. : 
- [x] When a friendship is confirmed, an additional row with reversed user-friend pair is created.
- [x] This should introduce opportunities for you to refactor your code e.g. you could find a user's friends only by the `user_id` in the friendships table. 
- [x] The PostsController#index should display posts by the logged in user and their friends, __not all posts__ ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/timeline.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made laudable progress in this milestone. Most features required seems to be working.__

__However, you've been informed that during the code review, you will get hints about implementing mutual friendships in the most efficient way, I'm here to do justice to that. Please check my comments below and make changes where necessary.__

**[ REQUIRED CHANGES ]**

- [x] When friendship is confirmed, you can create an additional row by adding this code snippet into your friendship model, like this:

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

- [x] Thanks to the snippet above, we can find user friends only by `user_id` in the friendships table:

```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

- [x] Also, User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

- [x] At the same time, User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

- [x] In order to get all posts written by a user and their friends, you can create and use a simple method in the User model (in order to NOT do it with Enumerables)

```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

- [x] You did not have any integration tests in your project. Kindly add

**COMMENTS**
Please note that the explanations above concerning implementing mutual friendship are to enable you to see an efficient implementation of mutual friendship. 

In my opinion, it does not mean that you should completely refactor yours to use the method stated above. However, you are advised to see how you can use it to improve your own version of the implementation.


* * *
**Please make changes where necessary and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You guys have done an excellent job so far. I commend your effort in implementing the previous changes.
However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] Some tests failed after your new changes.
- One of the changes you recently made (changing the button text from `Invite` to `Add Friend`) is causing about 2 of your test cases to fail. Kindly update the affected test cases.


**[ COMMENTS ]**

- [x] For good quality review and feedback, you should avoid pushing committed changes to the repo after you've already submitted the project for review. This is because the reviewer works with the version of the code he/she cloned and not the new changes you made after the reviewer has started the job. Please, take note.

* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by kevcap — APPROVED** [review]
# [STATUS] PROJECT APPROVED 🍾

### I really like your project! Congrats team, you guys did an excellent job, you have my approval to go ahead and merge this pull request!


## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

**Pull request merged**
